### ISSUE TITLE
Only fading/loading with one page

### ISSUE THREAD

**Issue by elisafern12** [Elkfox/Ajaxify#15]
Hello!

It is a great script! However, when after implementing it, I realize that it only seem to work with page one, then after all the image are loading at once. Or maybe the problem is that I think it is loading too fast and therefore, it looks like all the products are in one page instead of gradually loading. Is there a way to create a delay?

Am I missing something?

Thanks a bunch!

**Comment by ButsAndCats** [comment]
Hello @elisafern12 can you send me a link?

**Comment by ButsAndCats** [comment]
Closing as no response received leave a comment if you still need help.
