### ISSUE TITLE
Recursive Endless scrolling

### ISSUE THREAD

**Issue by GeneralA6** [Elkfox/Ajaxify#16]
while trying to scroll down really fast, if will load several requests at a time while they load and you continue scrolling it will load even more requests. 

Suggest you trying your code in a shop with a lot of products lets say 200+ so you can really see the scrolling bar shrinking very fast.
 
I fixed that logic issue .Check out my version of endless scrolling that i've built on your code as a base:
https://ecommerce.shopify.com/c/ecommerce-design/t/ajax-collection-products-endless-scrolling-504893

**Comment by ButsAndCats** [comment]
Yeh we are going to re-write this pretty soon. 

There is some quite naive code in it and there have been a few feature requests and optimisations that can be made.

I have never experienced an issue with scrolling down too fast and have tested this on a store with 10,000 products but there are some issues with the way it detects the scroll position so maybe thats related to the issue you were having.

Glad you found  a solution :+1:
