### ISSUE TITLE
Docs pages

### ISSUE THREAD

**Issue by Cam** [Elkfox/Ajaxify#6]
Let's have the docs pages for this (and all public projects) look like this...

<img src="https://d1zjcuqflbd5k.cloudfront.net/files/acc_33229/KcmK2?response-content-disposition=inline;%20filename=Screen%20Shot%20on%202017-05-20%20at%2014%3A56%3A26.png&Expires=1495256624&Signature=ZMP3v0cIDGuoQDQBxLgtJfVEAA7EyTRQXIn3iN7tJ4u6H28rlWZv6NlVQJlZu0cIH2JpypZkxPbdpIdeU48FUEiwf1W4SaBxdTzcyWRBwYtmOFNBFD46beNwKiC0s-474mGrOXSJgTSGRdB1BT8uhX5x7Txkm501~FjEYsxWVco_&Key-Pair-Id=APKAJTEIOJM3LSMN33SA">

**Comment by ButsAndCats** [comment]
https://elkfox.github.io/Ajaxify/

**Comment by Cam** [comment]
Ahh, damn. The attachment stopped working! Weird. I'm attaching it again to show some of the other changes I think we nee to make so that it is a little cleaner looking...
